# [AI] 通用参数化RISC-V Toolchain文件，支持不同厂商和LLVM/Clang
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_SYSTEM_VERSION 1)


# 可通过 -DRISCV_TRIPLE=xxx -DRISCV_ROOT_PATH=xxx -DRISCV_MARCH=xxx -DRISCV_MABI=xxx -DRISCV_USE_LLVM=ON 传参
set(RISCV_TRIPLE "riscv64-unknown-linux-gnu" CACHE STRING "GNU compiler triple")
set(RISCV_ROOT_PATH "" CACHE PATH "root path to riscv toolchain")
set(RISCV_MARCH "rv64gcv_zfh_zba_zicbop" CACHE STRING "RISC-V ISA extensions")
set(RISCV_MABI "lp64d" CACHE STRING "RISC-V ABI")
set(RISCV_USE_LLVM OFF CACHE BOOL "Use LLVM/Clang toolchain if ON, otherwise use GCC")
set(RISCV_SYSROOT "" CACHE PATH "Override sysroot path (defaults to <root>/sysroot or gcc -print-sysroot)")
set(RISCV_LIB_PATH "" CACHE PATH "Directory containing crtbeginS.o/libgcc (defaults to gcc -print-libgcc-file-name parent)")

if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(riscv)")
    message(STATUS "HOST SYSTEM ${CMAKE_HOST_SYSTEM_PROCESSOR}")
else()

    # 只在第一次include时强校验，try_compile等阶段丢失变量仅警告
    if (NOT DEFINED CMAKE_TOOLCHAIN_FILE_IS_INCLUDED)
        set(CMAKE_TOOLCHAIN_FILE_IS_INCLUDED TRUE)
        if (NOT RISCV_ROOT_PATH)
            if (DEFINED ENV{RISCV_ROOT_PATH})
                file(TO_CMAKE_PATH $ENV{RISCV_ROOT_PATH} RISCV_ROOT_PATH)
            elseif (DEFINED CMAKE_TRY_COMPILE)
                message(WARNING "[riscv64-toolchain] RISCV_ROOT_PATH missing during try_compile, falling back to empty path.")
            else()
                message(FATAL_ERROR "RISCV_ROOT_PATH env or -DRISCV_ROOT_PATH must be defined")
            endif()
        endif()
        if (RISCV_ROOT_PATH)
            set(ENV{RISCV_ROOT_PATH} "${RISCV_ROOT_PATH}")
        endif()
    else()
        if (NOT RISCV_ROOT_PATH)
            if (DEFINED ENV{RISCV_ROOT_PATH})
                file(TO_CMAKE_PATH $ENV{RISCV_ROOT_PATH} RISCV_ROOT_PATH)
            elseif (DEFINED CMAKE_TRY_COMPILE)
                message(WARNING "[riscv64-toolchain] RISCV_ROOT_PATH missing during try_compile, falling back to empty path.")
            else()
                message(WARNING "[riscv64-toolchain] RISCV_ROOT_PATH is not set in sub-CMake, may cause build issues.")
            endif()
        endif()
        if (RISCV_ROOT_PATH)
            set(ENV{RISCV_ROOT_PATH} "${RISCV_ROOT_PATH}")
        endif()
    endif()

    # 如果环境变量已有记录（例如父配置阶段设置），优先取出
    if (NOT RISCV_SYSROOT AND DEFINED ENV{RISCV_SYSROOT})
        file(TO_CMAKE_PATH $ENV{RISCV_SYSROOT} RISCV_SYSROOT)
    endif()

    # 尝试定位GNU交叉编译器，供后续sysroot/lib路径推导
    if (NOT RISCV_GNU_CC)
        set(_RISCV_TRIPLE_CANDIDATES ${RISCV_TRIPLE})
        if (RISCV_TRIPLE MATCHES "unknown-")
            string(REPLACE "unknown-" "" _RISCV_TRIPLE_NO_UNKNOWN ${RISCV_TRIPLE})
            list(APPEND _RISCV_TRIPLE_CANDIDATES ${_RISCV_TRIPLE_NO_UNKNOWN})
        endif()
        list(APPEND _RISCV_TRIPLE_CANDIDATES "riscv64-linux-gnu")
        foreach(_cand IN LISTS _RISCV_TRIPLE_CANDIDATES)
            find_program(RISCV_GNU_CC ${_cand}-gcc HINTS ${RISCV_ROOT_PATH}/bin)
            if (RISCV_GNU_CC)
                set(RISCV_GNU_TRIPLE ${_cand})
                get_filename_component(RISCV_GNU_BIN_DIR "${RISCV_GNU_CC}" DIRECTORY)
                get_filename_component(RISCV_GNU_ROOT "${RISCV_GNU_BIN_DIR}" DIRECTORY)
                set(ENV{RISCV_GNU_ROOT} "${RISCV_GNU_ROOT}")
                break()
            endif()
        endforeach()
    endif()

    # 推导sysroot：优先显式指定，其次<root>/sysroot，再尝试${RISCV_TRIPLE}-gcc -print-sysroot
    if (NOT RISCV_SYSROOT)
        if (RISCV_ROOT_PATH AND EXISTS "${RISCV_ROOT_PATH}/sysroot")
            set(RISCV_SYSROOT "${RISCV_ROOT_PATH}/sysroot")
        else()
            if (RISCV_GNU_CC)
                execute_process(
                    COMMAND ${RISCV_GNU_CC} -print-sysroot
                    OUTPUT_VARIABLE RISCV_GNU_SYSROOT
                    OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET)
                if (RISCV_GNU_SYSROOT AND EXISTS "${RISCV_GNU_SYSROOT}")
                    set(RISCV_SYSROOT "${RISCV_GNU_SYSROOT}")
                endif()
            endif()
        endif()
    endif()

    if (NOT RISCV_SYSROOT)
        if (DEFINED CMAKE_TRY_COMPILE)
            message(WARNING "[riscv64-toolchain] RISCV_SYSROOT is empty during try_compile, toolchain may fail to link.")
        else()
            message(FATAL_ERROR "RISCV_SYSROOT could not be determined; pass -DRISCV_SYSROOT=<path> or ensure ${RISCV_TRIPLE}-gcc -print-sysroot works")
        endif()
    endif()

    if (RISCV_SYSROOT)
        set(ENV{RISCV_SYSROOT} "${RISCV_SYSROOT}")
    endif()

    # 推导lib路径（crtbeginS.o、libgcc等）
    if (NOT RISCV_LIB_PATH)
        if (DEFINED ENV{RISCV_LIB_PATH})
            file(TO_CMAKE_PATH $ENV{RISCV_LIB_PATH} RISCV_LIB_PATH)
        elseif (RISCV_GNU_CC)
            execute_process(
                COMMAND ${RISCV_GNU_CC} -print-libgcc-file-name
                OUTPUT_VARIABLE RISCV_LIBGCC_FILE
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET)
            if (RISCV_LIBGCC_FILE)
                get_filename_component(RISCV_LIB_PATH "${RISCV_LIBGCC_FILE}" DIRECTORY)
            endif()
        endif()
    endif()

    if (RISCV_LIB_PATH)
        set(ENV{RISCV_LIB_PATH} "${RISCV_LIB_PATH}")
    endif()

    # 支持GCC和Clang自动切换
    if (RISCV_USE_LLVM)
        set(CMAKE_C_COMPILER   ${RISCV_ROOT_PATH}/bin/clang)
        set(CMAKE_CXX_COMPILER ${RISCV_ROOT_PATH}/bin/clang++)
        set(CMAKE_STRIP        ${RISCV_ROOT_PATH}/bin/llvm-strip)
        set(RISCV_SYSROOT_FLAG "--sysroot=${RISCV_SYSROOT}")
        set(RISCV_TARGET_FLAG  "--target=${RISCV_TRIPLE}")
        set(CMAKE_C_COMPILER_TARGET   ${RISCV_TRIPLE})
        set(CMAKE_CXX_COMPILER_TARGET ${RISCV_TRIPLE})
        set(CMAKE_C_FLAGS_INIT   "${RISCV_TARGET_FLAG} ${RISCV_SYSROOT_FLAG} -march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
        set(CMAKE_CXX_FLAGS_INIT "${RISCV_TARGET_FLAG} ${RISCV_SYSROOT_FLAG} -march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
    else()
        set(CMAKE_C_COMPILER   ${RISCV_ROOT_PATH}/bin/${RISCV_TRIPLE}-gcc)
        set(CMAKE_CXX_COMPILER ${RISCV_ROOT_PATH}/bin/${RISCV_TRIPLE}-g++)
        set(CMAKE_STRIP        ${RISCV_ROOT_PATH}/bin/${RISCV_TRIPLE}-strip)
        set(CMAKE_FIND_ROOT_PATH "${RISCV_SYSROOT}")
        set(CMAKE_SYSROOT        "${RISCV_SYSROOT}")
    endif()
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# 支持自定义march/mabi，兼容C/C++
if (RISCV_USE_LLVM)
    set(RISCV_LLVM_COMMON_FLAGS "${RISCV_TARGET_FLAG} ${RISCV_SYSROOT_FLAG} -march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
    if (RISCV_GNU_ROOT)
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} --gcc-toolchain=${RISCV_GNU_ROOT}")
        if (EXISTS "${RISCV_GNU_ROOT}/include/c++")
            file(GLOB _RISCV_CPP_VERSIONS RELATIVE "${RISCV_GNU_ROOT}/include/c++" "${RISCV_GNU_ROOT}/include/c++/*")
            list(FILTER _RISCV_CPP_VERSIONS INCLUDE REGEX "^[0-9].*")
            list(SORT _RISCV_CPP_VERSIONS)
            list(REVERSE _RISCV_CPP_VERSIONS)
            if (_RISCV_CPP_VERSIONS)
                list(GET _RISCV_CPP_VERSIONS 0 _RISCV_CPP_VER)
            endif()
            if (_RISCV_CPP_VER)
                set(RISCV_GNU_CXX_INCLUDE "${RISCV_GNU_ROOT}/include/c++/${_RISCV_CPP_VER}")
                set(RISCV_GNU_CXX_INCLUDE_TARGET "${RISCV_GNU_CXX_INCLUDE}/${RISCV_GNU_TRIPLE}")
            endif()
        endif()
    endif()
    if (RISCV_LIB_PATH)
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} -B${RISCV_LIB_PATH}")
    endif()
    if (RISCV_GNU_CXX_INCLUDE)
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} -isystem${RISCV_GNU_CXX_INCLUDE}")
    endif()
    if (RISCV_GNU_CXX_INCLUDE_TARGET AND EXISTS "${RISCV_GNU_CXX_INCLUDE_TARGET}")
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} -isystem${RISCV_GNU_CXX_INCLUDE_TARGET}")
    endif()
    if (RISCV_SYSROOT AND EXISTS "${RISCV_SYSROOT}/include")
        include_directories(SYSTEM "${RISCV_SYSROOT}/include")
    endif()
    if (RISCV_GNU_CXX_INCLUDE)
        include_directories(SYSTEM "${RISCV_GNU_CXX_INCLUDE}")
        if (EXISTS "${RISCV_GNU_CXX_INCLUDE}/${RISCV_GNU_TRIPLE}")
            include_directories(SYSTEM "${RISCV_GNU_CXX_INCLUDE}/${RISCV_GNU_TRIPLE}")
        endif()
    endif()
    set(CMAKE_C_FLAGS   "${RISCV_LLVM_COMMON_FLAGS} ${CMAKE_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${RISCV_LLVM_COMMON_FLAGS} ${CMAKE_CXX_FLAGS}")
    find_program(RISCV_LLD ld.lld HINTS ${RISCV_ROOT_PATH}/bin NO_DEFAULT_PATH)
    if (RISCV_LLD)
        set(RISCV_LLD_FLAG "-fuse-ld=${RISCV_LLD}")
    else()
        set(RISCV_LLD_FLAG "-fuse-ld=lld")
    endif()
    set(RISCV_LLVM_LINK_FLAGS "${RISCV_TARGET_FLAG} ${RISCV_SYSROOT_FLAG} ${RISCV_LLD_FLAG}")
    if (RISCV_LIB_PATH)
        set(RISCV_LLVM_LINK_FLAGS "${RISCV_LLVM_LINK_FLAGS} -L${RISCV_LIB_PATH} -B${RISCV_LIB_PATH}")
    endif()
    set(CMAKE_EXE_LINKER_FLAGS "${RISCV_LLVM_LINK_FLAGS} ${CMAKE_EXE_LINKER_FLAGS} -latomic")
else()
    set(CMAKE_C_FLAGS   "-march=${RISCV_MARCH} -mabi=${RISCV_MABI} ${CMAKE_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "-march=${RISCV_MARCH} -mabi=${RISCV_MABI} ${CMAKE_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -latomic")
endif()
